First stage
monika1127/invoicer pull request #2
Opened 2021-01-08 18:48 UTC by monika1127

2021-01-10 17:18 UTC, korczas requested changes
- format code.
- remove multiple empty rows - you can use empty row to separate some logic, but 3,4,5 empty rows are bad.

App looks nice and clean. After quite a long break with CSS and HTML you're still fresh. Good job.

2021-01-10 17:18 UTC, korczas commented on .eslintcache
> +[{"C:\\Users\\Monika\\Desktop\\programowanie\\4_react\\invoicer\\src\\index.js":"1","C:\\Users\\Monika\\Desktop\\programowanie\\4_react\\invoicer\\src\\App.js":"2","C:\\Users\\Monika\\Desktop\\progra
add `.eslintcache` to your `.gitignore` file

2021-01-10 17:18 UTC, korczas commented on db.json
> +  ]
add empty line on end of file

2021-01-10 17:18 UTC, korczas commented on package.json
> +    "cliui": "^7.0.4",
`cliui` library seems to be redundant in your app.\
run `npm uninstall cliui`

2021-01-10 17:18 UTC, korczas commented on public/index.html
> +    ></script>
font awesome is an old school. Use .svg instead

2021-01-10 17:18 UTC, korczas commented on src/App.css
> +  font-size: 12px;
your body font-size is set for 12px, so duplicating it here seems redundant

2021-01-10 17:18 UTC, korczas commented on src/assets/images/clock2.min.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><path d="M16 0C7.163 0 0 7.163 0 16s7.163 16 16 16 16-7.163 16-16S24.837 0 16 0zm4.586 23.414L14 16.828V8h4v7.172l5.414 5.414-2.829 2.82
add empty new line at the end of file

2021-01-10 17:18 UTC, korczas commented on src/assets/images/cog.svg
> +</svg>
add empty new line at the end of file

2021-01-10 17:18 UTC, korczas commented on src/assets/images/printer-black.svg
> +</svg>
add empty new line at the end of file

2021-01-10 17:18 UTC, korczas commented on src/assets/images/printer.svg
> +</svg>
add empty new line at the end of file

2021-01-10 17:18 UTC, korczas commented on package.json
> +    "cliui": "^7.0.4",
I assume you had installed `json-server` globally. Please add `json-server` to your local dependencies.
`npm i json-server`

2021-01-10 17:18 UTC, korczas commented on src/components/invoices/InvoiceItem.js
> +import PropTypes from 'prop-types'
good practice for imports is to group them by type. Import libraries first, empty line, components, empty line, icons, empty line, styles, empty line

```
import React, { Component } from 'react'
import PropTypes from 'prop-types'

import Button from '../layout/button/Button'

import { ReactComponent as Search } from '../../assets/images/search.svg'
import { ReactComponent as Clock } from '../../assets/images/clock2.svg'
import { ReactComponent as Printer } from '../../assets/images/printer-black.svg'
import { ReactComponent as Arrow } from '../../assets/images/redo2.svg'
```

2021-01-10 17:18 UTC, korczas commented on src/components/layout/Spinner/Spinner.js
> +export default Spinner
new line

2021-01-10 17:18 UTC, korczas commented on src/components/invoices/InvoiceDetails/InvoiceDetails.js
> +import { ReactComponent as Set } from '../../../assets/images/cog.svg'
group imports

2021-01-10 17:18 UTC, korczas commented on src/components/invoices/InvoiceDetails/InvoiceDetails.js
> +
✂️

2021-01-10 17:18 UTC, korczas commented on src/components/invoices/InvoiceDetails/InvoiceDetails.js
> +
assume that `price` is netto, and calculate brutto based on this

2021-01-10 17:18 UTC, korczas commented on src/components/invoices/InvoicesList.js
> +            .then(res => res.json())
you can skip this `this.setState({ loading: true })` in cDM - that makes unnecessary render. Set you default state to `{..., loading: true, ...}`

2021-01-10 17:18 UTC, korczas commented on src/components/layout/table/Table.js
> +export default Table
- code format
- consider different approach:

```
static propTypes ={
  columns: PropTypes.array.isRequired,
  RowComponent: PropTypes. element.isRequired,
  data: PropTypes.arrayOf(Proptypes.object).isRequired,
}

...

<tbody>
  {this.props.data.map(row => <RowComponent {...row} />}
</tbody>

```

2021-01-11 16:56 UTC, monika1127 commented on db.json
> +  ]
dlaczego?

2021-01-11 17:03 UTC, monika1127 commented on src/components/invoices/InvoiceDetails/InvoiceDetails.js
> +import { ReactComponent as Set } from '../../../assets/images/cog.svg'
?

2021-01-13 23:06 UTC, korczas commented
@monika1127 plz push updates

2021-01-15 11:46 UTC, merged